# Generated by Django 5.2.16 on 2026-07-22 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (بالدولار)')),
                ('daily_limit', models.PositiveIntegerField(verbose_name='الحد الأقصى للنشر اليومي')),
                ('features', models.TextField(help_text='كل ميزة في سطر منفصل', verbose_name='المميزات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('is_custom', models.BooleanField(default=False, verbose_name='مخصصة للشركات (تتطلب تواصل)')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('crypto', 'عملات رقمية'), ('local', 'بوابة محلية')], max_length=20, verbose_name='بوابة الدفع')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف العملية في البوابة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('failed', 'فشلت')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.customerprofile')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionpackage')),
            ],
        ),
    ]
