# Generated by Django 5.2.16 on 2026-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'دولار أمريكي (USD)'), ('EGP', 'جنيه مصري (EGP)')], default='USD', max_length=10, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
    ]
