# Generated by Django 5.2.16 on 2026-07-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_currency_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم المرسل (المحفظة)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verified_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='رقم العملية الموثق'),
        ),
    ]
