# Generated by Django 5.2.16 on 2026-07-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_sender_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('crypto', 'عملات رقمية'), ('local', 'بوابة محلية'), ('paymob', 'Paymob (بطاقة بنكية)')], max_length=20, verbose_name='بوابة الدفع'),
        ),
    ]
