# Generated by Django 5.2.16 on 2026-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_devicepairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fallback_notified',
            field=models.BooleanField(default=False, help_text='لتفادي إرسال رسالة واتساب مكررة لطلب سكرين شوت التحويل عند انقطاع اتصال تطبيق المراقبة', verbose_name='تم إرسال رسالة التأكيد اليدوي'),
        ),
    ]
