# Generated by Django 5.2.16 on 2026-07-27 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_fallback_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='annual_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك سنوي (%)'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='monthly_articles_limit',
            field=models.PositiveIntegerField(default=0, help_text='للعرض فقط حالياً في لوحة التحكم وصفحة الباقات، بدون إنفاذ فعلي في محرك النشر. 0 = لا يُعرض حد شهري منفصل.', verbose_name='الحد الأقصى للنشر الشهري'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='quarterly_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك ربع سنوي (%)'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='semiannual_discount_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك نصف سنوي (%)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي (3 أشهر)'), ('semiannual', 'نصف سنوي (6 أشهر)'), ('annual', 'سنوي (12 شهر)')], default='monthly', max_length=12, verbose_name='فترة الاشتراك'),
        ),
    ]
