# Generated by Django 5.2.16 on 2026-07-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_subscriptionpackage_annual_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='تُميَّز هذه الباقة بشارة "الأكثر شعبية" وتُبرز بصرياً في صفحات الأسعار. يفضّل تفعيلها لباقة واحدة فقط في نفس الوقت.', verbose_name='الأكثر شعبية'),
        ),
    ]
