# Generated by Django 5.2.16 on 2026-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_subscriptionpackage_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='page_closed_notified',
            field=models.BooleanField(default=False, help_text='لتفادي إرسال رسالة واتساب مكررة لو العميل أغلق/أعاد فتح صفحة الدفع أكثر من مرة', verbose_name='تم إرسال رسالة إغلاق صفحة الدفع'),
        ),
    ]
