# Generated by Django 5.2.16 on 2026-07-31 21:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_transaction_page_closed_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAddonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (بالدولار)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('is_recommended', models.BooleanField(default=False, help_text='تُميَّز هذه الباقة بشارة "الأكثر شعبية" وتُبرز بصرياً في صفحات الأسعار. يفضّل تفعيلها لباقة واحدة فقط في نفس الوقت.', verbose_name='الأكثر شعبية')),
                ('quarterly_discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك ربع سنوي (%)')),
                ('semiannual_discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك نصف سنوي (%)')),
                ('annual_discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك سنوي (%)')),
                ('monthly_articles_limit', models.PositiveIntegerField(default=0, help_text='بعد الوصول لهذا العدد يتوقف النشر التلقائي على فيسبوك حتى بداية الشهر التالي أو الترقية. 0 = بدون حد (غير محدود).', verbose_name='الحد الأقصى لعدد الأخبار المنشورة على فيسبوك شهرياً')),
                ('show_watermark', models.BooleanField(default=False, help_text='يُفعَّل عادة في الباقة المجانية كحافز للترقية لباقة بدون علامة مائية.', verbose_name='إظهار علامة "Sahafi Hub" على التصميم')),
            ],
            options={
                'verbose_name': 'باقة نشر فيسبوك',
                'verbose_name_plural': 'باقات نشر فيسبوك',
            },
        ),
        migrations.AlterField(
            model_name='subscriptionpackage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='included_facebook_addon_plan',
            field=models.ForeignKey(blank=True, help_text='اختر باقة نشر فيسبوك تُمنح تلقائياً مجاناً لمن يشترك في هذه الباقة. اتركه فارغاً لو الباقة دي لا تشمل خدمة فيسبوك.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='included_in_packages', to='payments.facebookaddonplan', verbose_name='تشمل باقة فيسبوك التالية مجاناً'),
        ),
    ]
