# Generated by Django 5.2.16 on 2026-08-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_facebookaddonplan_alter_subscriptionpackage_name_and_more'),
        ('syndicator', '0021_wordpresssite_facebook_addon_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='facebook_addon_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.facebookaddonplan', verbose_name='باقة فيسبوك (لو نوع المنتج إضافة فيسبوك)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_type',
            field=models.CharField(choices=[('package', 'باقة نشر'), ('facebook_addon', 'باقة نشر فيسبوك')], default='package', max_length=20, verbose_name='نوع المنتج'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wp_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_addon_transactions', to='syndicator.wordpresssite', verbose_name='الموقع المستهدف (لباقات فيسبوك)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionpackage'),
        ),
    ]
