# Generated by Django 5.2.16 on 2026-08-13 07:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_transaction_facebook_addon_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsAddonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر (بالدولار)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('is_recommended', models.BooleanField(default=False, help_text='تُميَّز هذه الباقة بشارة "الأكثر شعبية" وتُبرز بصرياً في صفحات الأسعار. يفضّل تفعيلها لباقة واحدة فقط في نفس الوقت.', verbose_name='الأكثر شعبية')),
                ('quarterly_discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك ربع سنوي (%)')),
                ('semiannual_discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك نصف سنوي (%)')),
                ('annual_discount_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم - اشتراك سنوي (%)')),
                ('max_concurrent_active_campaigns', models.PositiveIntegerField(default=1, help_text='0 = بدون حد.', verbose_name='أقصى عدد حملات نشطة في نفس الوقت')),
                ('max_daily_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='سقف أمان لكل حملة عبر معالج الإنشاء، لحماية العميل غير الخبير من إدخال ميزانية كبيرة بالخطأ.', max_digits=10, verbose_name='أقصى ميزانية يومية للحملة (USD)')),
            ],
            options={
                'verbose_name': 'باقة إدارة إعلانات فيسبوك',
                'verbose_name_plural': 'باقات إدارة إعلانات فيسبوك',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_type',
            field=models.CharField(choices=[('package', 'باقة نشر'), ('facebook_addon', 'باقة نشر فيسبوك'), ('ads_addon', 'باقة إدارة إعلانات فيسبوك')], default='package', max_length=20, verbose_name='نوع المنتج'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ads_addon_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.adsaddonplan', verbose_name='باقة إدارة إعلانات (لو نوع المنتج إدارة إعلانات)'),
        ),
    ]
