# Generated by Django 5.2.16 on 2026-07-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجموعة مصادر الأخبار',
                'verbose_name_plural': 'مجموعات مصادر الأخبار',
            },
        ),
        migrations.AddField(
            model_name='aisource',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='syndicator.aisourcegroup', verbose_name='المجموعة'),
        ),
    ]
