# Generated by Django 5.2.16 on 2026-07-22 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0002_aisourcegroup_aisource_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPConnectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='كود الربط (Token)')),
                ('client_name', models.CharField(help_text='لتمييز الكود ولمن يتبع', max_length=255, verbose_name='اسم العميل / الموقع')),
                ('is_used', models.BooleanField(default=False, verbose_name='تم الاستخدام؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wp_site', models.ForeignKey(blank=True, help_text='سيتم ملؤه تلقائياً بعد نجاح الربط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='syndicator.wordpresssite', verbose_name='الموقع المرتبط')),
            ],
            options={
                'verbose_name': 'كود ربط ووردبريس',
                'verbose_name_plural': 'أكواد ربط ووردبريس',
                'ordering': ['-created_at'],
            },
        ),
    ]
