# Generated by Django 5.2.16 on 2026-07-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0003_wpconnectiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='source_groups',
            field=models.ManyToManyField(blank=True, related_name='wp_sites', to='syndicator.aisourcegroup', verbose_name='مجموعات المصادر المرتبطة'),
        ),
    ]
