# Generated by Django 5.2.16 on 2026-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0004_wordpresssite_source_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpconnectiontoken',
            name='package_daily_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='الحد اليومي للباقة المشتراة'),
        ),
    ]
