# Generated by Django 5.2.16 on 2026-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0005_wpconnectiontoken_package_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='wallet_number',
            field=models.CharField(default='201099437596', help_text='رقم الهاتف (فودافون كاش) الذي سيحول إليه العملاء قيمة الاشتراك.', max_length=50, verbose_name='رقم المحفظة لاستقبال التحويلات'),
        ),
    ]
