# Generated by Django 5.2.16 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0006_aisettings_wallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية/الاشتراك'),
        ),
        migrations.AddField(
            model_name='wpconnectiontoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء صلاحية الكود'),
        ),
    ]
