# Generated by Django 5.2.16 on 2026-07-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_has_used_trial'),
        ('syndicator', '0007_wordpresssite_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpconnectiontoken',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='مصدر الملكية الفعلي للكود — لا تُستخدم client_name للتحقق من الملكية', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_tokens', to='accounts.customerprofile', verbose_name='العميل المالك'),
        ),
        migrations.AlterField(
            model_name='wpconnectiontoken',
            name='client_name',
            field=models.CharField(help_text='للعرض فقط (تسمية الكود)، وليس مصدر الملكية', max_length=255, verbose_name='اسم العميل / الموقع'),
        ),
    ]
