# Generated by Django 5.2.16 on 2026-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0009_backfill_wpconnectiontoken_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='facebook_addon_trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='خدمة النشر التلقائي على فيسبوك مدفوعة بشكل منفصل عن الاشتراك الأساسي. اترك هذا الحقل فارغاً لتفعيل دائم (بعد الدفع)، أو حدد تاريخاً لمنح تجربة مجانية تُعطَّل تلقائياً بعده حتى لو ظل مفتاح التفعيل أعلاه مفعّلاً.', null=True, verbose_name='نهاية الفترة التجريبية المجانية (خدمة فيسبوك)'),
        ),
    ]
