# Generated by Django 5.2.16 on 2026-07-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0010_wordpresssite_facebook_addon_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='enable_local_wallet_gateway',
            field=models.BooleanField(default=True, verbose_name='إظهار المحافظ المحلية (فودافون كاش) كطريقة دفع'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='enable_paymob_gateway',
            field=models.BooleanField(default=True, verbose_name='إظهار Paymob (بطاقات مصرية) كطريقة دفع'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='enable_paypal_gateway',
            field=models.BooleanField(default=True, verbose_name='إظهار PayPal كطريقة دفع'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='support_whatsapp_number',
            field=models.CharField(blank=True, help_text='الرقم الذي يظهر للعملاء للتواصل المباشر (زر واتساب عائم في الموقع وصفحة تواصل معنا). اكتبه بصيغة دولية بدون + أو مسافات (مثال: 201099437596). اتركه فارغاً لإخفاء زر التواصل.', max_length=50, null=True, verbose_name='رقم واتساب الدعم الفني'),
        ),
    ]
