# Generated by Django 5.2.16 on 2026-07-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0011_aisettings_enable_local_wallet_gateway_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisourcegroup',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'مجموعة مصادر الأخبار', 'verbose_name_plural': 'مجموعات مصادر الأخبار'},
        ),
        migrations.AddField(
            model_name='aisourcegroup',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً إذا كانت هذه مجموعة رئيسية. اختر مجموعة رئيسية لجعل هذه مجموعة فرعية تابعة لها.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='syndicator.aisourcegroup', verbose_name='القسم الرئيسي'),
        ),
    ]
