# Generated by Django 5.2.16 on 2026-07-29 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0013_seed_source_group_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisourcegroup',
            name='is_price_articles_group',
            field=models.BooleanField(default=False, help_text='عند التفعيل، تُستخدم تصنيفات ووردبريس المرتبطة بهذا القسم الفرعي تلقائياً لتصنيف مقالات الأسعار الحية (الذهب، الفضة، الدولار، الحديد، الإسمنت، الدواجن، الأسماك، الخضار، العملات العربية) عند نشرها. يجب أن يكون قسماً فرعياً واحداً فقط في كل مرة.', verbose_name='مجموعة مقالات الأسعار'),
        ),
        migrations.CreateModel(
            name='SourceGroupWPCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_category_ids', models.CharField(blank=True, default='', help_text='معرّفات (IDs) تصنيفات الووردبريس المطابقة لهذا القسم الفرعي على هذا الموقع، مفصولة بفاصلة. أول معرّف يُستخدم كتصنيف أساسي (SEO) والباقي كتصنيفات إضافية. مثال: 5,12,20', max_length=255, verbose_name='معرّفات تصنيفات ووردبريس')),
                ('source_group', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wp_category_maps', to='syndicator.aisourcegroup', verbose_name='القسم الفرعي')),
                ('wp_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_group_category_maps', to='syndicator.wordpresssite', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'ربط قسم فرعي بتصنيف ووردبريس',
                'verbose_name_plural': 'روابط الأقسام الفرعية بتصنيفات ووردبريس',
                'unique_together': {('wp_site', 'source_group')},
            },
        ),
    ]
