# Generated by Django 5.2.16 on 2026-07-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0016_seed_scraper_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimportlog',
            name='meta_description',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='الوصف التعريفي (Meta Description)'),
        ),
        migrations.AlterField(
            model_name='aiimportlog',
            name='status',
            field=models.CharField(choices=[('success', 'نجاح (Success)'), ('failed', 'فشل (Failed)'), ('pending_image', 'بانتظار اختيار صورة (Pending Image)')], default='success', max_length=20),
        ),
    ]
