# Generated by Django 5.2.16 on 2026-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0017_aiimportlog_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='social_badge_text',
            field=models.CharField(blank=True, default='', help_text='يظهر في قالبي "إخباري احترافي" و"عاجل" فوق العنوان مباشرةً، مثال: تقرير، عاجل، حصري. اتركه فارغاً لاستخدام "خبر" (أو "عاجل" تلقائياً في قالب العاجل).', max_length=30, verbose_name='نص الوسم فوق العنوان'),
        ),
        migrations.AlterField(
            model_name='socialsharepost',
            name='template_used',
            field=models.CharField(choices=[('news_ribbon', 'إخباري احترافي (لوجو أعلى + وسم + تدرج سفلي فوق العنوان)'), ('breaking_news', 'عاجل (كتلة لون سفلية بوسم وعنوان محاذى لليمين)'), ('bottom_banner', 'شريط سفلي (صورة كاملة + شريط عنوان أسفل)'), ('boxed_card', 'بطاقة مؤطرة (صورة مع إطار وصندوق عنوان)'), ('split_block', 'تقسيم علوي/سفلي (صورة أعلى وكتلة لون بالعنوان أسفل)')], max_length=20, verbose_name='القالب المستخدم'),
        ),
        migrations.AlterField(
            model_name='wordpresssite',
            name='social_template',
            field=models.CharField(choices=[('news_ribbon', 'إخباري احترافي (لوجو أعلى + وسم + تدرج سفلي فوق العنوان)'), ('breaking_news', 'عاجل (كتلة لون سفلية بوسم وعنوان محاذى لليمين)'), ('bottom_banner', 'شريط سفلي (صورة كاملة + شريط عنوان أسفل)'), ('boxed_card', 'بطاقة مؤطرة (صورة مع إطار وصندوق عنوان)'), ('split_block', 'تقسيم علوي/سفلي (صورة أعلى وكتلة لون بالعنوان أسفل)')], default='news_ribbon', max_length=20, verbose_name='قالب تصميم الصورة'),
        ),
    ]
