# Generated by Django 5.2.16 on 2026-07-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0018_wordpresssite_social_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='social_logo_position',
            field=models.CharField(choices=[('top_right', 'أعلى اليمين'), ('top_center', 'أعلى المنتصف'), ('top_left', 'أعلى اليسار')], default='top_left', help_text='يتحكم في مكان لوجو الموقع في قالبي "إخباري احترافي" و"عاجل" فقط.', max_length=20, verbose_name='مكان اللوجو في التصميم'),
        ),
    ]
