# Generated by Django 5.2.16 on 2026-07-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0019_wordpresssite_social_logo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpresssite',
            name='social_logo_position',
            field=models.CharField(choices=[('top_right', 'أعلى اليمين'), ('top_center', 'أعلى المنتصف'), ('top_left', 'أعلى اليسار')], default='top_left', help_text='يتحكم في مكان لوجو الموقع أعلى التصميم، في كل القوالب.', max_length=20, verbose_name='مكان اللوجو في التصميم'),
        ),
    ]
