# Generated by Django 5.2.16 on 2026-07-31 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_facebookaddonplan_alter_subscriptionpackage_name_and_more'),
        ('syndicator', '0020_alter_wordpresssite_social_logo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='facebook_addon_plan',
            field=models.ForeignKey(blank=True, help_text='تحدد الحد الأقصى الشهري لعدد الأخبار المنشورة على فيسبوك، وهل يظهر علامة "Sahafi Hub" على التصميم. اتركه فارغاً لعدم فرض أي حد شهري ولا علامة مائية (تفعيل يدوي بدون باقة محددة).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.facebookaddonplan', verbose_name='باقة نشر فيسبوك الحالية'),
        ),
    ]
