# Generated by Django 5.2.16 on 2026-08-01 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_transaction_facebook_addon_plan_and_more'),
        ('syndicator', '0021_wordpresssite_facebook_addon_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpconnectiontoken',
            name='included_facebook_addon_plan',
            field=models.ForeignKey(blank=True, help_text='تُنسخ من SubscriptionPackage.included_facebook_addon_plan وقت الشراء - تُمنح تلقائياً للموقع عند ربطه بهذا الكود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.facebookaddonplan', verbose_name='باقة فيسبوك المُضمّنة مع الباقة المشتراة'),
        ),
    ]
