# Generated by Django 5.2.16 on 2026-08-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0022_wpconnectiontoken_included_facebook_addon_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisource',
            name='use_proxy',
            field=models.BooleanField(default=False, help_text='فعّله لو هذا المصدر يحظر IP السيرفر تحديداً (بيرجع 403 أو يدخل في حلقة تحويلات) رغم أنه يعمل بشكل طبيعي من أي مكان آخر. يتطلب ضبط SCRAPING_PROXY_URL في إعدادات السيرفر أولاً - بدونه يُتجاهل هذا الخيار ويتم الجلب المباشر كالمعتاد.', verbose_name='التوجيه عبر بروكسي'),
        ),
    ]
