# Generated by Django 5.2.16 on 2026-08-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndicator', '0024_seed_source_failure_spike_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirroredFeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000, verbose_name='الرابط الأصلي (اللي هيتم جلبه فعلياً عبر GitHub Actions)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_config', to='syndicator.aisource', verbose_name='المصدر')),
            ],
            options={
                'verbose_name': 'Mirrored Feed Config',
                'verbose_name_plural': 'Mirrored Feed Configs',
            },
        ),
    ]
