# Generated by Django 5.2.16 on 2026-08-13 07:22

import django.db.models.deletion
import syndicator.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
        ('payments', '0012_adsaddonplan_alter_transaction_product_type_and_more'),
        ('syndicator', '0023_aisource_use_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_adset_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف المجموعة الإعلانية')),
                ('optimization_goal', models.CharField(blank=True, default='', max_length=50, verbose_name='هدف التحسين')),
                ('billing_event', models.CharField(blank=True, default='', max_length=50, verbose_name='حدث الفوترة')),
                ('targeting_spec', models.JSONField(blank=True, default=dict, verbose_name='بيانات الاستهداف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_creation', 'جاري الإنشاء'), ('active', 'نشطة'), ('paused', 'متوقفة مؤقتاً'), ('completed', 'منتهية'), ('error', 'خطأ')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجموعة إعلانية',
                'verbose_name_plural': 'المجموعات الإعلانية',
            },
        ),
        migrations.CreateModel(
            name='AdAccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_ad_account_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف حساب الإعلانات (act_...)')),
                ('facebook_business_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف Business Manager')),
                ('ad_account_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم حساب الإعلانات')),
                ('currency', models.CharField(blank=True, default='', max_length=10, verbose_name='عملة حساب الإعلانات')),
                ('access_token', syndicator.fields.EncryptedCharField(blank=True, max_length=1000, null=True, verbose_name='توكن وصول (Long-Lived User Token بصلاحية ads_management)')),
                ('status', models.CharField(choices=[('not_connected', 'غير متصل'), ('connected', 'متصل'), ('needs_reauth', 'يحتاج إعادة ربط'), ('error', 'خطأ')], default='not_connected', max_length=20, verbose_name='حالة الاتصال')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('ads_addon_trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الاشتراك/الفترة التجريبية')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الربط')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحقق من صلاحية الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ads_addon_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.adsaddonplan', verbose_name='باقة إدارة الإعلانات الحالية')),
                ('wp_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_account_connection', to='syndicator.wordpresssite', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'ربط حساب إعلانات فيسبوك',
                'verbose_name_plural': 'ربط حسابات إعلانات فيسبوك',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_creative_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف المحتوى الإعلاني')),
                ('source_type', models.CharField(choices=[('existing_post', 'ترويج منشور فيسبوك موجود'), ('article_cover', 'صورة غلاف الخبر')], max_length=20, verbose_name='مصدر المحتوى')),
                ('image_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='رابط الصورة')),
                ('primary_text', models.TextField(blank=True, default='', verbose_name='النص الأساسي')),
                ('headline', models.CharField(blank=True, default='', max_length=255, verbose_name='العنوان')),
                ('call_to_action', models.CharField(default='LEARN_MORE', max_length=30, verbose_name='زر الدعوة لاتخاذ إجراء')),
                ('destination_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='رابط الوجهة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.adset', verbose_name='المجموعة الإعلانية')),
            ],
            options={
                'verbose_name': 'محتوى إعلاني',
                'verbose_name_plural': 'المحتوى الإعلاني',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_ad_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف الإعلان')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الإعلان')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_creation', 'جاري الإنشاء'), ('active', 'نشطة'), ('paused', 'متوقفة مؤقتاً'), ('completed', 'منتهية'), ('error', 'خطأ')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adcreative', verbose_name='المحتوى الإعلاني')),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adset', verbose_name='المجموعة الإعلانية')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحملة')),
                ('objective', models.CharField(choices=[('OUTCOME_TRAFFIC', 'زيادة الزيارات لموقعك'), ('OUTCOME_ENGAGEMENT', 'تفاعل أكبر مع المنشور'), ('OUTCOME_AWARENESS', 'أكبر انتشار ممكن')], max_length=30, verbose_name='الهدف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_creation', 'جاري الإنشاء'), ('active', 'نشطة'), ('paused', 'متوقفة مؤقتاً'), ('completed', 'منتهية'), ('error', 'خطأ')], default='draft', max_length=20, verbose_name='الحالة')),
                ('facebook_campaign_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف الحملة على فيسبوك')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الميزانية اليومية')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('destination_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='رابط الوجهة')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ads.adaccountconnection', verbose_name='حساب الإعلانات')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='syndicator.article', verbose_name='الخبر المُروَّج له')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customerprofile', verbose_name='أُنشئت بواسطة')),
                ('social_share_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='syndicator.socialsharepost', verbose_name='منشور فيسبوك المُروَّج له')),
            ],
            options={
                'verbose_name': 'حملة إعلانية',
                'verbose_name_plural': 'الحملات الإعلانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adset',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_sets', to='ads.campaign', verbose_name='الحملة'),
        ),
        migrations.CreateModel(
            name='AdInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='مرات الظهور')),
                ('reach', models.PositiveIntegerField(default=0, verbose_name='الوصول')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='النقرات')),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإنفاق')),
                ('ctr', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='معدل النقر (%)')),
                ('cpc', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='تكلفة النقرة')),
                ('cpm', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='تكلفة الألف ظهور')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='استجابة API الخام')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='ads.campaign', verbose_name='الحملة')),
            ],
            options={
                'verbose_name': 'أداء يومي للحملة',
                'verbose_name_plural': 'الأداء اليومي للحملات',
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
