# Generated by Django 5.2.16 on 2026-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_seed_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='facebook_post_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='معرّف منشور فيسبوك (بدون سجل SocialSharePost محلي)'),
        ),
    ]
