# Generated by Django 5.2.16 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='has_used_trial',
            field=models.BooleanField(default=False, verbose_name='استخدم الفترة التجريبية'),
        ),
    ]
