# Generated by Django 5.2.16 on 2026-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='has_used_ads_trial',
            field=models.BooleanField(default=False, verbose_name='استخدم الفترة التجريبية لإدارة الإعلانات'),
        ),
    ]
