# Generated by Django 5.2.16 on 2026-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customerprofile_has_used_ads_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='auth0_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='معرف Auth0'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الواتساب'),
        ),
    ]
