# Generated by Django 5.2.16 on 2026-08-01 10:06

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُنشأ تلقائياً من العنوان إذا تُرك فارغاً.', max_length=220, unique=True, verbose_name='الرابط المختصر')),
                ('excerpt', models.TextField(help_text='ملخص قصير يظهر في قائمة المدونة ونتائج البحث (وكـ meta description).', max_length=300, verbose_name='مقتطف')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='المحتوى')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/', verbose_name='صورة الغلاف')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقالة مدونة',
                'verbose_name_plural': 'مقالات المدونة',
                'ordering': ['-published_at'],
            },
        ),
    ]
